/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 casa-processed.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/casa-processed.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
          <mesh geometry={nodes.mesh_0.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -14.77]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_1.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -14.44]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_2.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -14.11]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_3.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -13.78]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_4.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -13.46]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_5.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -13.13]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_6.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -12.8]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_7.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -12.47]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_8.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -12.14]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_9.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -11.82]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_10.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -11.49]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_11.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -11.16]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_12.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -10.83]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_13.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -10.5]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_14.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -10.18]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_15.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -9.85]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_16.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -9.52]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_17.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -9.19]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_18.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -8.86]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_19.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -8.54]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_20.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -8.21]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_21.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -7.88]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_22.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -7.55]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_23.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -21.66]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_24.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -21.33]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_25.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -21]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_26.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -20.67]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_27.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -20.35]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_28.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -20.02]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_29.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -19.69]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_30.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -19.36]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_31.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -19.03]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_32.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -18.71]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_33.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -18.38]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_34.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -18.05]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_35.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -17.72]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_36.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -17.39]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_37.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -17.07]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_38.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -16.74]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_39.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -16.41]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_40.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -16.08]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_41.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -15.75]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_42.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -15.42]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_43.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -15.1]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_44.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -22.97]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_45.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -22.64]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_46.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -22.31]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_47.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -21.99]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_48.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -24.61]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_49.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -24.28]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_50.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -23.96]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_51.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -23.63]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_52.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[58.68, 8.86, -23.3]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.mesh_53.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[35.47, 8.86, -14.8]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_54.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[33.5, 8.86, -14.8]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_55.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[41.37, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_56.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[39.4, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_57.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[37.44, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_58.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[45.31, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_59.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[43.34, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_60.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[57.12, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_61.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[55.15, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_62.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[53.18, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_63.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[51.22, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_64.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[49.25, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_65.geometry} material={materials['woods & plastics.finish carpentry.wood.pine.png']} position={[47.28, 8.86, -7.22]} rotation={[0, 1.57, 0]} />
          <mesh geometry={nodes.mesh_66.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_67.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_68.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_69.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_70.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_71.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_72.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_73.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_74.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_75.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_76.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_77.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_78.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_79.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_80.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_81.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_82.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_83.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_84.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_85.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_86.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_87.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_88.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_89.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_90.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_91.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_92.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_93.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_94.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_95.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_96.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_97.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_98.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_99.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_100.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_101.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_102.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_103.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_104.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_105.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_106.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_107.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_108.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_109.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_110.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_111.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_112.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_113.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_114.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_115.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_116.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_117.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_118.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_119.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_120.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_121.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_122.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_123.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_124.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_125.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_126.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_127.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_128.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_129.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_130.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_131.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_132.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_133.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_134.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_135.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_136.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_137.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_138.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_139.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_140.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_141.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_142.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_143.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_144.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_145.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_146.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_147.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_148.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_149.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_150.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_151.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_152.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_153.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_154.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_155.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_156.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_157.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_158.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_159.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_160.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_161.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_162.geometry} material={materials['R40,G40,B40']} />
          <mesh geometry={nodes.mesh_163.geometry} material={materials['R168,G168,B168']} />
          <mesh geometry={nodes.mesh_164.geometry} material={materials['R218,G227,B224']} />
          <mesh geometry={nodes.mesh_165.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_166.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_167.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_168.geometry} material={materials['R247,G247,B239']} />
          <mesh geometry={nodes.mesh_169.geometry} material={materials['R224,G178,B126']} />
          <mesh geometry={nodes.mesh_170.geometry} material={materials['R247,G247,B239']} />
          <mesh geometry={nodes.mesh_171.geometry} material={materials['R224,G178,B126']} />
          <mesh geometry={nodes.mesh_172.geometry} material={materials['R65,G29,B25']} />
          <mesh geometry={nodes.mesh_173.geometry} material={materials['R65,G29,B25']} />
          <mesh geometry={nodes.mesh_174.geometry} material={materials['R112,G95,B78']} />
          <mesh geometry={nodes.mesh_175.geometry} material={materials['R178,G229,B255']} />
          <mesh geometry={nodes.mesh_176.geometry} material={materials['R65,G29,B25']} />
          <mesh geometry={nodes.mesh_177.geometry} material={materials['R65,G29,B25']} />
          <mesh geometry={nodes.mesh_178.geometry} material={materials['R112,G95,B78']} />
          <mesh geometry={nodes.mesh_179.geometry} material={materials['R178,G229,B255']} />
          <mesh geometry={nodes.mesh_180.geometry} material={materials['R65,G29,B25']} />
          <mesh geometry={nodes.mesh_181.geometry} material={materials['R65,G29,B25']} />
          <mesh geometry={nodes.mesh_182.geometry} material={materials['R112,G95,B78']} />
          <mesh geometry={nodes.mesh_183.geometry} material={materials['R178,G229,B255']} />
          <mesh geometry={nodes.mesh_184.geometry} material={materials['R65,G29,B25']} />
          <mesh geometry={nodes.mesh_185.geometry} material={materials['R65,G29,B25']} />
          <mesh geometry={nodes.mesh_186.geometry} material={materials['R247,G247,B239']} />
          <mesh geometry={nodes.mesh_187.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_188.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_189.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_190.geometry} material={materials['R196,G146,B67']} />
          <mesh geometry={nodes.mesh_191.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_192.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_193.geometry} material={materials['R196,G146,B67']} />
          <mesh geometry={nodes.mesh_194.geometry} material={materials['R95,G63,B61']} />
          <mesh geometry={nodes.mesh_195.geometry} material={materials['R126,G84,B47']} />
          <mesh geometry={nodes.mesh_196.geometry} material={materials['R95,G63,B61']} />
          <mesh geometry={nodes.mesh_197.geometry} material={materials['R126,G84,B47']} />
          <mesh geometry={nodes.mesh_198.geometry} material={materials['R95,G63,B61']} />
          <mesh geometry={nodes.mesh_199.geometry} material={materials['R126,G84,B47']} />
          <mesh geometry={nodes.mesh_200.geometry} material={materials['R64,G0,B64']} />
          <mesh geometry={nodes.mesh_201.geometry} material={materials['R211,G211,B211']} />
          <mesh geometry={nodes.mesh_202.geometry} material={materials['R255,G255,B255']} />
          <mesh geometry={nodes.mesh_203.geometry} material={materials['R64,G0,B64']} />
          <mesh geometry={nodes.mesh_204.geometry} material={materials['R211,G211,B211']} />
          <mesh geometry={nodes.mesh_205.geometry} material={materials['R255,G255,B255']} />
          <mesh geometry={nodes.mesh_206.geometry} material={materials['R64,G0,B64']} />
          <mesh geometry={nodes.mesh_207.geometry} material={materials['R211,G211,B211']} />
          <mesh geometry={nodes.mesh_208.geometry} material={materials['R255,G255,B255']} />
          <mesh geometry={nodes.mesh_209.geometry} material={materials['R64,G0,B64']} />
          <mesh geometry={nodes.mesh_210.geometry} material={materials['R211,G211,B211']} />
          <mesh geometry={nodes.mesh_211.geometry} material={materials['R255,G255,B255']} />
          <mesh geometry={nodes.mesh_212.geometry} material={materials['R42,G42,B42']} />
          <mesh geometry={nodes.mesh_213.geometry} material={materials['R63,G63,B56']} />
          <mesh geometry={nodes.mesh_214.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_215.geometry} material={materials['R226,G211,B191']} />
          <mesh geometry={nodes.mesh_216.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_217.geometry} material={materials['R226,G211,B191']} />
          <mesh geometry={nodes.mesh_218.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_219.geometry} material={materials['R247,G247,B239']} />
          <mesh geometry={nodes.mesh_220.geometry} material={materials['R0,G0,B255']} />
          <mesh geometry={nodes.mesh_221.geometry} material={materials['R160,G160,B160']} />
          <mesh geometry={nodes.mesh_222.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_223.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_224.geometry} material={materials['R105,G96,B88']} />
          <mesh geometry={nodes.mesh_225.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_226.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_227.geometry} material={materials['R105,G96,B88']} />
          <mesh geometry={nodes.mesh_228.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_229.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_230.geometry} material={materials['R105,G96,B88']} />
          <mesh geometry={nodes.mesh_231.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_232.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_233.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_234.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_235.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_236.geometry} material={materials['R212,G179,B113']} />
          <mesh geometry={nodes.mesh_237.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_238.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_239.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_240.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_241.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_242.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_243.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_244.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_245.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_246.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_247.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_248.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_249.geometry} material={materials['R146,G120,B101']} />
          <mesh geometry={nodes.mesh_250.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_251.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_252.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_253.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_254.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_255.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_256.geometry} material={materials['R247,G247,B239']} />
          <mesh geometry={nodes.mesh_257.geometry} material={materials['R247,G247,B247']} />
          <mesh geometry={nodes.mesh_258.geometry} material={materials['R249,G239,B230']} />
          <mesh geometry={nodes.mesh_259.geometry} material={materials['R249,G239,B230']} />
          <mesh geometry={nodes.mesh_260.geometry} material={materials['R249,G239,B230']} />
          <mesh geometry={nodes.mesh_261.geometry} material={materials['R64,G0,B64']} />
          <mesh geometry={nodes.mesh_262.geometry} material={materials['R64,G0,B64']} />
          <mesh geometry={nodes.mesh_263.geometry} material={materials['R66,G143,B54']} />
          <mesh geometry={nodes.mesh_264.geometry} material={materials['R127,G127,B127']} />
          <mesh geometry={nodes.mesh_265.geometry} material={materials['R0,G128,B192']} />
          <mesh geometry={nodes.mesh_266.geometry} material={materials['R0,G128,B192']} />
          <mesh geometry={nodes.mesh_267.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_268.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_269.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_270.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_271.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_272.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_273.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_274.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_275.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_276.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_277.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_278.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_279.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_280.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_281.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_282.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_283.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_284.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_285.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_286.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_287.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_288.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_289.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_290.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_291.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_292.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_293.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_294.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_295.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_296.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_297.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_298.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_299.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_300.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_301.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_302.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_303.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_304.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_305.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_306.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_307.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_308.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_309.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_310.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_311.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_312.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_313.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_314.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_315.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_316.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_317.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_318.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_319.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_320.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_321.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_322.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_323.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_324.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_325.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_326.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_327.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_328.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_329.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_330.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_331.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_332.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_333.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_334.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_335.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_336.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_337.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_338.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_339.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_340.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_341.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_342.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_343.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_344.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_345.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_346.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_347.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_348.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_349.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_350.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_351.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_352.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_353.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_354.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_355.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_356.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_357.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_358.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_359.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_360.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_361.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_362.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_363.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_364.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_365.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_366.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_367.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_368.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_369.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_370.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_371.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_372.geometry} material={materials['R234,G198,B147']} />
          <mesh geometry={nodes.mesh_373.geometry} material={materials['R234,G198,B147']} />
          <mesh geometry={nodes.mesh_374.geometry} material={materials['R234,G198,B147']} />
          <mesh geometry={nodes.mesh_375.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_376.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_377.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_378.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_379.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_380.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_381.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_382.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_383.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_384.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_385.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_386.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_387.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_388.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_389.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_390.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_391.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_392.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_393.geometry} material={materials['R77,G47,B28']} />
          <mesh geometry={nodes.mesh_394.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_395.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_396.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_397.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_398.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_399.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_400.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_401.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_402.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_403.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_404.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_405.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_406.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_407.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_408.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_409.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_410.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_411.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_412.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_413.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_414.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_415.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_416.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_417.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_418.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_419.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_420.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_421.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_422.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_423.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_424.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_425.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_426.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_427.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_428.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_429.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_430.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_431.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_432.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_433.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_434.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_435.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_436.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_437.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_438.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_439.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_440.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_441.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_442.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_443.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_444.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_445.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_446.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_447.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_448.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_449.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_450.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_451.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_452.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_453.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_454.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_455.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_456.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_457.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_458.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_459.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_460.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_461.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_462.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_463.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_464.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_465.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_466.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_467.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_468.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_469.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_470.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_471.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_472.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_473.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_474.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_475.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_476.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_477.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_478.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_479.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_480.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_481.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_482.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_483.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_484.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_485.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_486.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_487.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_488.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_489.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_490.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_491.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_492.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_493.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_494.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_495.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_496.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_497.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_498.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_499.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_500.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_501.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_502.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_503.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_504.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_505.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_506.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_507.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_508.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_509.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_510.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_511.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_512.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_513.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_514.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_515.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_516.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_517.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_518.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_519.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_520.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_521.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_522.geometry} material={materials['R121,G75,B51']} />
          <mesh geometry={nodes.mesh_523.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_524.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_525.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_526.geometry} material={materials['R249,G249,B249']} />
          <mesh geometry={nodes.mesh_527.geometry} material={materials['R128,G128,B128']} />
          <mesh geometry={nodes.mesh_528.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_529.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_530.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_531.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_532.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_533.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_534.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_535.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_536.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_537.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_538.geometry} material={materials['R233,G233,B228']} />
          <mesh geometry={nodes.mesh_539.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_540.geometry} material={materials['R120,G120,B120']} />
          <mesh geometry={nodes.mesh_541.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_542.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_543.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_544.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_545.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_546.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_547.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_548.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_549.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_550.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_551.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_552.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_553.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_554.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_555.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_556.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_557.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_558.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_559.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_560.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_561.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_562.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_563.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_564.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_565.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_566.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_567.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_568.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_569.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_570.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_571.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_572.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_573.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_574.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_575.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_576.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_577.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_578.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_579.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_580.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_581.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_582.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_583.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_584.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_585.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_586.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_587.geometry} material={materials['R236,G240,B239']} />
          <mesh geometry={nodes.mesh_588.geometry} material={materials['R17,G17,B17']} />
          <mesh geometry={nodes.mesh_589.geometry} material={materials['R0,G0,B0']} />
          <mesh geometry={nodes.mesh_590.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_591.geometry} material={materials['R216,G216,B204']} />
          <mesh geometry={nodes.mesh_592.geometry} material={materials['R208,G208,B208']} />
          <mesh geometry={nodes.mesh_593.geometry} material={materials['R208,G208,B208']} />
          <group position={[49.25, 0, 2.62]} rotation={[0, -1.57, 0]}>
            <mesh geometry={nodes.mesh_594.geometry} material={materials['R210,G159,B95']} />
            <mesh geometry={nodes.mesh_595.geometry} material={materials['R236,G240,B239']} />
            <mesh geometry={nodes.mesh_596.geometry} material={materials['R118,G70,B51']} />
          </group>
          <group position={[52.07, -0.59, -65.73]}>
            <group position={[-4.97, 0, -1.23]}>
              <mesh geometry={nodes.mesh_597.geometry} material={materials['R171,G171,B171']} />
              <mesh geometry={nodes.mesh_598.geometry} material={materials['R0,G0,B0']} />
              <mesh geometry={nodes.mesh_599.geometry} material={materials['R0,G0,B255']} />
            </group>
          </group>
          <group position={[20.38, 0, -28.68]} rotation={[0, 1.57, 0]}>
            <mesh geometry={nodes.mesh_600.geometry} material={materials['woods & plastics.finish carpentry.wood.red birch.png']} />
            <mesh geometry={nodes.mesh_601.geometry} material={materials['R66,G40,B29']} />
            <mesh geometry={nodes.mesh_602.geometry} material={materials['R164,G172,B176']} />
          </group>
          <group position={[41.21, 0, -37.86]} rotation={[0, -1.57, 0]}>
            <mesh geometry={nodes.mesh_603.geometry} material={materials['woods & plastics.finish carpentry.wood.red birch.png']} />
            <mesh geometry={nodes.mesh_604.geometry} material={materials['R66,G40,B29']} />
            <mesh geometry={nodes.mesh_605.geometry} material={materials['R164,G172,B176']} />
          </group>
          <group position={[16.27, 0, -0.76]} rotation={[0, 1.57, 0]}>
            <mesh geometry={nodes.mesh_606.geometry} material={materials['woods & plastics.finish carpentry.wood.red birch.png']} />
            <mesh geometry={nodes.mesh_607.geometry} material={materials['R66,G40,B29']} />
            <mesh geometry={nodes.mesh_608.geometry} material={materials['R164,G172,B176']} />
          </group>
          <group position={[25.64, 0, 10.87]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_609.geometry} material={materials['woods & plastics.finish carpentry.wood.red birch.png']} />
            <mesh geometry={nodes.mesh_610.geometry} material={materials['R66,G40,B29']} />
            <mesh geometry={nodes.mesh_611.geometry} material={materials['R164,G172,B176']} />
          </group>
          <group position={[19.72, 0, -4.63]} rotation={[0, 1.57, 0]}>
            <mesh geometry={nodes.mesh_612.geometry} material={materials['R135,G74,B45']} />
            <mesh geometry={nodes.mesh_613.geometry} material={materials['R164,G172,B176']} />
          </group>
          <group position={[21.77, 0, 2.84]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_614.geometry} material={materials['R135,G74,B45']} />
            <mesh geometry={nodes.mesh_615.geometry} material={materials['R164,G172,B176']} />
          </group>
          <group position={[23.82, 0, -4.63]} rotation={[0, -1.57, 0]}>
            <mesh geometry={nodes.mesh_616.geometry} material={materials['R135,G74,B45']} />
            <mesh geometry={nodes.mesh_617.geometry} material={materials['R164,G172,B176']} />
          </group>
          <group position={[27.68, 0, -65.73]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_618.geometry} material={materials['woods & plastics.finish carpentry.wood.red birch.png']} />
            <mesh geometry={nodes.mesh_619.geometry} material={materials['R66,G40,B29']} />
            <mesh geometry={nodes.mesh_620.geometry} material={materials['R164,G172,B176']} />
          </group>
          <mesh geometry={nodes.mesh_621.geometry} material={materials['R208,G208,B208']} position={[30.96, 0, -35.96]} />
          <mesh geometry={nodes.mesh_622.geometry} material={materials['R208,G208,B208']} position={[43.59, 0, -35.96]} />
          <mesh geometry={nodes.mesh_623.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_624.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_625.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_626.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_627.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_628.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_629.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_630.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_631.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_632.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_633.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_634.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_635.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_636.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_637.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_638.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_639.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_640.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_641.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_642.geometry} material={materials['R221,G217,B195']} />
          <mesh geometry={nodes.mesh_643.geometry} material={materials['R234,G234,B234']} />
          <mesh geometry={nodes.mesh_644.geometry} material={materials['R234,G234,B234']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/casa-processed.gltf')
